employee/config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'

end

employee/app/models/list.rb
class List < ActiveRecord::Base
	validates :name, {presence: true}
	
end

employee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

employee/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
        @lists = List.order("age DESC ").first(5)      #order("salary").group("department ").first(5)
       #if params.has_key?(:order) and params[:order] == 'age'
       #@lists = List.order("age DESC")

     #elsif params.has_key?(:order) and params[:order] == 'department'
     #  @lists = List.order("department")
     # elsif params.has_key?(:order) and params[:order] == 'salary'
      # @lists = List.order("salary")
    # elsif params.has_key?(:order) and params[:order] == 'age'
     #  @lists = List.where("age >= ?" , "60")

    # else 
    #   @lists = List.all
    # end  
  

 end  

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :email, :age, :salary, :department)
    end
end

employee/app/helpers/application_helper.rb
module ApplicationHelper
end

employee/app/helpers/lists_helper.rb
module ListsHelper
end

employee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Employee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

employee/app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

employee/app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

employee/app/views/lists/index.html.erb
<h1>Listing lists</h1>
<h2><a href="/lists?order=age">order by age</a></h2>
<h2><a href="/lists?order=department">order by department</a></h2>
<h2><a href="/lists?order=salary">order by salary</a></h2>
<h2><a href="/lists?order=age">retired people</a></h2>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.id %></td>
        <td><%= list.name.upcase %></td>
        <td><%= list.email %></td>
        <td><%= list.age %></td>
        <td><%= list.salary %></td>
        <td><%= list.department %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

employee/app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

employee/app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @list.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @list.age %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @list.salary %>
</p>

<p>
  <strong>Department:</strong>
  <%= @list.department %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>